//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiToolkit.Analyzer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiToolkit.Analyzer.Resources.CodeFixerStrings", typeof(CodeFixerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partial get method.
        /// </summary>
        internal static string PartialMethodFixerEquivalenceKey {
            get {
                return ResourceManager.GetString("PartialMethodFixerEquivalenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partial get method for the property &apos;{0}&apos;.
        /// </summary>
        internal static string PartialMethodFixerTittle {
            get {
                return ResourceManager.GetString("PartialMethodFixerTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partial keyword.
        /// </summary>
        internal static string PartialPropertyFixerEquivalenceKey {
            get {
                return ResourceManager.GetString("PartialPropertyFixerEquivalenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partial keyword for the property &apos;{0}&apos;.
        /// </summary>
        internal static string PartialPropertyFixerTittle {
            get {
                return ResourceManager.GetString("PartialPropertyFixerTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partial set method.
        /// </summary>
        internal static string PartialSetMethodFixerEquivalenceKey {
            get {
                return ResourceManager.GetString("PartialSetMethodFixerEquivalenceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partial set method for the property &apos;{0}&apos;.
        /// </summary>
        internal static string PartialSetMethodFixerTittle {
            get {
                return ResourceManager.GetString("PartialSetMethodFixerTittle", resourceCulture);
            }
        }
    }
}
